### ISSUE TITLE
Can't solve this issue

### ISSUE THREAD

**Issue by tjikaljedy** [GoteoFoundation/goteo#1]
Hi teams, 

I am trying to run goteo latest version from github. as following is my machine enviroment:
1. windows 10 64bit with npm, mysql, composer, PEAR installed under WAMP 64 (latest)
2. inside gruntfiles.js bit changes to implement in my machine

GOTEO = {

```
localURL: 'usaharakyat.net',
localPort:8081,

// to override this parameter, simply copy:
// var/php/php.ini file to config/php.ini
// and edit it with your own data
phpINI: 'D:/workspace/usr/java/wamp/bin/apache/apache2.4.9/bin/php.ini',

configFile: 'config/settings.yml'
```

};
1. When running with command grunt serve and try to login the system throw me an errors like:

←[31m[2015-12-04 22:03:38] main.ERROR: USER NOTICE: 'Only variables should be p
ssed by reference' at WebProcessor.php 106: .... HttpKernel.php 139 calling call_user_func_array()   <unknown file> <unknown line> calling login ...  EventDispatcher.php 18 1 calling call_user_func()   <unknown file> <unknown line> calling loginSuccess

I trying to trace this error in HttpKernel.php 139 and tried to print $controller is EMPTY

// controller arguments
 $arguments = $this->resolver->getArguments($request, $controller);
// call controller
 $response = call_user_func_array($controller, $arguments);

Same error when I am using VAGRANT box.

Thank you for being knows this error can solve by you.

Thx

**Comment by microstudi** [comment]
You should'nt be changing the Gruntfile.js. Change the config/settings.yml instead and place your php.ini into var/php/php.ini. This way your copy of Gruntfile.js can be updated in the future without further changes.

I think this problem is the same as this:
http://stackoverflow.com/questions/4636166/only-variables-should-be-passed-by-reference

In this case into the file WebProcessor.
I'll make a patch
Thanks for noticing

**Comment by tjikaljedy** [comment]
Thx microstudi, 

talking about this application, i really thx to you. and for your information, I will use your apps in Indonesia, this application to serve SME industry. and also operate by NGO. So if you dont mine I will helping you as long i can, specially testing apps.

Thx

**Comment by microstudi** [comment]
That's great. Maybe you can provide a translation? any help will be welcomed.
By the way, be aware that we wil be posting many changes/fixes this month so keep up to date your code!

**Comment by tjikaljedy** [comment]
sure. i provided translation and any changes will posted to your email.

**Comment by tjikaljedy** [comment]
Hi Ivan,

The error is gone, but i still cannot login as root/root, the admin page
not come out , the browser back to login page every time i did submit
button,

Thx

**Comment by tjikaljedy** [comment]
Finally i solve this problem, just added some of sub domain in host files

en, es refer to main domain or sub

Thx
