### ISSUE TITLE
Could not find an option named "compass" after grunt build

### ISSUE THREAD

**Issue by oyale** [GoteoFoundation/goteo#100]
After make the guide's previous steps, after  I run `grunt build:dist`, it throws the following error:
`Running "sass:devel" (sass) task
Could not find an option named "compass".`

If I add the --force option, it finish with a website without any css, js or images. I don't know why, except for the two first images (that doesn't found), it look for the assets in localhost:8081; the url for assets is already changed in /config/settings.yml

**Comment by oyale** [comment]
Partially solved after setting env var GOTEO_CONFIG_FILE, and commented the assets line, it does load some images & css now; The site is not functional anyway. Now, it throws this errors:

Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING (Chrome) in index.php:1

Content security policy the page's settings blocked the loading of a resource (Firefox) at all scripts

**Comment by microstudi** [comment]
It seems that you don't have correctly installed sass-compass (ruby gems).
Here you have more info:
http://goteofoundation.github.io/goteo/docs/developers/environment.html

Otherwise, just docker to build your images, it everything already installed.

**Comment by oyale** [comment]
Thank you!

Starting from scratch worked

**Comment by microstudi** [comment]
glad to know!
