### ISSUE TITLE
Compiling sass

### ISSUE THREAD

**Issue by ramoncodit** [GoteoFoundation/goteo#109]
Good evening,
I tried to configure the project to work in a integration server, without using docker containers.
So, after to have cloned the project, I realised that I needed to compile public/assets/sass style sheets in order to have available an assets folder in root path.
So when I tried to compile them as follows:
sass --update public/assets/sass:assets/css -f
I got an error:
```
  directory assets/css
      write assets/css/bootstrap-editable.css
      write assets/css/bootstrap-editable.css.map
      error public/assets/sass/components/_custom_animations.scss (Line 1: File to import not found or unreadable: compass/css3.
Load path: /home/ramon/projectes/php/occ2018/public/assets/sass)
      error public/assets/sass/layouts/_layout.scss (Line 1: File to import not found or unreadable: compass/css3.
Load path: /home/ramon/projectes/php/occ2018/public/assets/sass)
      write assets/css/project.css
      write assets/css/project.css.map
      write assets/css/project_charts.css
      write assets/css/project_charts.css.map
      error public/assets/sass/typeahead.scss (Line 2: File to import not found or unreadable: compass/css3.
Load path: /home/ramon/projectes/php/occ2018/public/assets/sass)
```
So I googled for a solution and I got the conclusion (maybe wrong) that I needed compass. I downloaded it from : 
- https://github.com/Compass/compass/tree/stable/core/stylesheets/compass
And I put on public/assets/sass folder.
Next, I tried compiling again, with new error result:
```
write assets/css/bootstrap-editable.css
      write assets/css/bootstrap-editable.css.map
      error /home/ramon/projectes/php/occ2018/public/assets/sass/compass/_support.scss (Line 323: (full-support: true) isn't a valid CSS value.)
      error /home/ramon/projectes/php/occ2018/public/assets/sass/compass/_support.scss (Line 323: (full-support: true) isn't a valid CSS value.)
      write assets/css/project.css
      write assets/css/project.css.map
      write assets/css/project_charts.css
      write assets/css/project_charts.css.map
      error /home/ramon/projectes/php/occ2018/public/assets/sass/compass/_support.scss (Line 323: (full-support: true) isn't a valid CSS value.)
```
So I suppose is a wrong Compass version. Before try/catch more things, I'd prefered to ask here.

Finally, one last thing, when comparing with installation using docker containers, I realised that the compilation of sass style sheets were done automatically in a .tmp dir on root of the project.
In config dockerfile: 
- docker/php/Dockerfile
I saw that into docker container, it installs Sass Gem and Compass gem:
```
RUN gem install sass -v 3.4.23
RUN gem install compass
RUN npm install -g grunt-cli
RUN ln -s /usr/bin/nodejs /usr/bin/node
```
but couldn't figure out why didn't work in local environment, without docker and compiling only with sass.

What I'm doing wrong/missed out ?
Thanks in advance,
Greetings

**Comment by microstudi** [comment]
It may be that you have many sass versions installed and the system is using the wrong one (it happened to me as well). That's why probably the best option is to use the docker image.
This process is described in http://goteofoundation.github.io/goteo/docs/developers/environment.html#installing-everything-in-your-own-machine

You can run the command `gem list|grep sass` to see what versions of sass you have installed.
