### ISSUE TITLE
About template > modifications, change template 

### ISSUE THREAD

**Issue by beinetwork** [GoteoFoundation/goteo#11]
Hi,

1) I can not change the template, do you have the dedicated document on this subject other than http://goteofoundation.github.io/goteo/docs/developers/templates.html ?

2) The template published on https://fr.goteo.org available?
3) Graphic animations (Example 1: https://fr.goteo.org/project/yoibextigo , Example 2: https://fr.goteo.org/project/yoibextigo/participate) are available?

Thank you for your help!
@microstudi @Goteo

**Comment by microstudi** [comment]
Hi, when I have time I'll write something more extensive.
Meanwhile you should investigate a little bit the code.

Mainlines:
1. The template system overwritten by plugins. This is commented in [Plugins](http://goteofoundation.github.io/goteo/docs/developers/extend.html). You shoul make your own plugin (a folder inside `extend`, the a a folder called `Resources`, you can replicate any existing template on the main Resources/template there. 
   For example,  `Resources/templates/responsive/project/main.php` will be overwriten by a plugin having a file like `extend/plugin-name/Resources/templates/responsive/project` (be aware that the plugin must be activated in settings.yml). Also remember that the template system uses [Foil](http://www.foilphp.it/) check its documentation as well.
2. Maybe some parts of it are customized (I think it's the matchfunding part of it), however the main page is currently build according the modules activated in the admin home (/admin/home), you must activate or deactive items.
3. Yes they are included. In the views `Resources/templates/responsive/project/partials/chart_costs.php` and `Resources/templates/responsive/project/partials/chart_amount.php`

**Comment by beinetwork** [comment]
Hi Ivan,
Thank you for your explanations.

To change the theme with "EXTEND plugin" I read the documentation (also plates php, etc.) but I can not change the template for responsive /home.php (project) and also the other pages of responsive template.

Could you give me the full example for this (change of template project page "default" to "responsive" with the plugin) please?

I've added as friends on Facebook because I want to discuss a win-win cooperation with you.
@microstudi

**Comment by microstudi** [comment]
ok, I'll give some example but I'm gonna need to find some time, I'll try to have something for you this week

**Comment by beinetwork** [comment]
Okay Super :-D

Thank you for accepting my invitation on Facebook to be able to talk together when you have time.

**Comment by beinetwork** [comment]
Hi Yvan,

It’s possible to have a copy of the template (and features) of current goteo.org?
This would be better for us to be able to develop our project.
Can I become a goteo-contributor to translate into French (goteo, goteo-stats etc.)?
You can contact me here or email (steiner.tijs@gmail.com)

@microstudi

**Comment by microstudi** [comment]
You'are asking for many different thinks, goteo-stats is another project, it uses the api which is another project as well.
https://github.com/GoteoFoundation/goteo-stats
https://github.com/GoteoFoundation/goteo-api

The template it's included, what features are ou talking about? Please be aware that we provide the code and some (voluntary) support, but we cannot do all the job for you. 
Technical assistance will be provided if you ask for specific questions, the more specific the question the better for us to provide a good answer. Generic question like this aren't easy to respond.

We are open to any contribution, feel free to make any pull request!

**Comment by beinetwork** [comment]
Hi Yvan,

Thank you for your last post, I try now to ask a clear and detailed question ;)

Question: How to publishing responsive project page template:

So, how to configure publishing responsive page project in default for project section into the website? 
We must do what changes in what file? routes ? or other files?

This question is how to publish by default at: /Resources/templates/responsive/project/home.php (pages is in the / project) to replace: /Resources/templates/default/project/index.html.

To get the same result as: https://fr.goteo.org/project/yoibextigo

Regards,

Tijs

@microstudi

**Comment by microstudi** [comment]
You don't have to replace anything, it should work. That design is included, and it's the default.
The choosing of the responsive theme it's done in the controller, for example in the ProjectsController.php(496):

``` php
    private function view($id, $show, $post = null, Request $request) {
        //activamos la cache para esta llamada
        \Goteo\Core\DB::cache(true);

        //Set the responsive theme
        View::setTheme('responsive');
```

Are you seeing anything different in your installation?

**Comment by beinetwork** [comment]
Thx Yvan for this solution but…

There was no line :: View setTheme ( 'responsive'); in the ProjectsController.php.
I try to add but it listed: PROJECT / INDEX IS NOT A VALID TEMPLATE NAME.
ERROR 500 
http://www.upmytalent.com/project/project-passing-today
The default theme is displayed correctly

Here is the file (493) https://github.com/beinetwork/upmytalent.com/blob/master/ProjectController.php
what to do?
@microstudi

**Comment by beinetwork** [comment]
I found the solution to prolème I said before:
I have configured the line 587 (> project / index to project / home)
But now the theme is not displayed properly, there is something to do for the theme?

@microstudi

**Comment by microstudi** [comment]
I will have to look into it, I'll to replicate this behaviour and I'll tou something soon

**Comment by beinetwork** [comment]
that's okay, thank u!

**Comment by beinetwork** [comment]
If his can help you, here is the the current apache error log:

[Wed Jun 15 13:25:37.160322 2016] [:error] [pid 30933] [client 178.196.35.194:60468] USER NOTICE: 'Invalid argument supplied for foreach()' at /var/www/vhosts/upmytalent.com/httpdocs/goteo/Resources/templates/responsive/project/layout.php 85: /var/www/vhosts/upmytalent.com/httpdocs/goteo/dist/index.php 59 calling run() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/src/Goteo/Application/App.php 179 calling handle() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/vendor/symfony/http-kernel/HttpKernel.php 62 calling handleRaw() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/vendor/symfony/http-kernel/HttpKernel.php 139 calling call_user_func_array() | <unknown file> <unknown line> calling indexAction() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/src/Goteo/Controller/ProjectController.php 39 calling view() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/src/Goteo/Controller/ProjectController.php 587 calling render() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/src/Goteo/Application/View.php 55 calling render() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/vendor/foil/foil/src/Engine.php 211 calling doRender() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/vendor/foil/foil/src/Engine.php 307 calling render() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/vendor/foil/foil/src/Template/Template.php 241 calling collect() | /var/www/vhosts/upmytalent.com/httpdocs/goteo/vendor/foil/foil/src/Template/Template.php 287 calling require()

**Comment by microstudi** [comment]
indeed helps, thanks

**Comment by beinetwork** [comment]
Do you know where is the problem?
Do you need something else?

**Comment by beinetwork** [comment]
Hi Yvan,

So you have everything to find this template to display error, i've add on github the fils of goteo into your website (No include folder: node_modules, grunt and vendor - And clear cons sensible data (DB, mail))
https://github.com/beinetwork/goteo-current-server-files

That will he be able to help you?

website url: http://www.upmytalent.com/

If you want an FTP or SFTP access (console) give me an email address where I can send you this data

**Comment by microstudi** [comment]
I'm gonna send you an private email now, but please, you should change the way you publish your changes:
The proper way to do it is to fork this repo, then commit your changes to your own repo (ideally to a new custom branch). This way we all can see your changes without so much effort (even comment them). And it's important to not change the license, this software it's already licensed under the AGPL terms.

**Comment by beinetwork** [comment]
Hi,
I emailed you all for you now.

Best,
@

**Comment by tjikaljedy** [comment]
hi bein,

can you share how to make project UI with new themes

Thx

**Comment by beinetwork** [comment]
hi @tjikaljedy 

Have u telegram to speak together?

**Comment by tjikaljedy** [comment]
i use skype with name: tjikaljedy and WA: 08569899905

thx
