### ISSUE TITLE
Ayuda con goteo

### ISSUE THREAD

**Issue by lalbertogc** [GoteoFoundation/goteo#119]
Estimados, me pueden enviar mas información de como instalar la plataforma goteo en server linux centos7 o debian9 o si se puede instalar en ambiente wampserver, se los agradecería mucho.
Luis Alberto Gutierrez.

**Comment by davidbeig** [comment]
Hola Luis Alberto,

En la documentación de Goteo tienes los pasos a seguir para poder realizar la instalación, así como viene preparado para levantar la plataforma con docker-compose como con vagrant.

Te has encontrado con algun error en concreto con la instalación? 

Saludos!
