### ISSUE TITLE
Banner- Video

### ISSUE THREAD

**Issue by lizeth9797** [GoteoFoundation/goteo#122]
Hi guys,
I'm wondering, can I add a video(mp4)  in the banner?

![banner](https://user-images.githubusercontent.com/36308437/59892784-2d906900-93a0-11e9-94c5-2e8fbcea221f.png)

**Comment by microstudi** [comment]
You will have to overwrite the banner view to do that.

Check this out about how to make a simple plugin:
https://goteofoundation.github.io/goteo/docs/developers/extend.html
