### ISSUE TITLE
Euro Currency shown in the projects

### ISSUE THREAD

**Issue by lizeth9797** [GoteoFoundation/goteo#123]
Hi all,
Do you know how can I change the euro currency shown in the projects? I'd like to change it to mexican currency

Thanks and regards

![currency](https://user-images.githubusercontent.com/36308437/60069386-2a66e700-96d8-11e9-90b8-e88bd9a9abb9.png)

**Comment by microstudi** [comment]
Please, take a look of how currencies work.
This file controls the currencies in the system:
https://github.com/GoteoFoundation/goteo/blob/devel/src/Goteo/Application/Currency.php

Default currencies processed by the previous file are defined in here:
https://github.com/GoteoFoundation/goteo/blob/devel/Resources/currencies.yml

If you don't want to mess with the original code, the best way to proceed would be to create a plugin that overrides the currencies system. Something like the following in the `start.php` (change values and symbols accordingly)  should do the trick:

```php
Goteo\Appication\Currency::setCurrenciesAvailable([[
            'id' => 'EUR',
            'name' => 'Euro',
            'symbol' => '€',
            'html' => '€', // legacy var
            'thousands' => '.',
            'thou' => '.', // Legacy var
            'decimal'  => ',',
            'dec'  => ',', // legacy var
            'active' => true
        ]]);
```

**Comment by getsei** [comment]
I saw some currencies conversion amount is set to 0. Eg, I added Pakistani Rupee as PKR but the converted amount is 0. Korean Won as KRW or Australian Dollar as AUD works fine.

**Comment by getsei** [comment]
but all currencies are defined in floatrates.com/daily/$BASE$.xml file
