### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by raulsibaja7** [GoteoFoundation/goteo#124]
Hi everyone, can someone help me with this issue?
Thank you.

raul@raul-hp:~/git/goteo$ sudo docker/up
[sudo] password for raul: 
Starting goteo-geoip     ... done
Starting goteo-php       ... done
Starting goteo-mailhog   ... done
Starting goteo-webserver ... done
Starting goteo-mariadb   ... done
Attaching to goteo-php, goteo-webserver, goteo-mariadb, goteo-mailhog, goteo-geoip
goteo-php    | Executing: [./docker/php/init.sh]
goteo-php    | useradd: user 'goteo' already exists
goteo-mailhog | WARNING: no logs are available with the 'none' log driver
goteo-php    | usermod: no changes
goteo-php    | Do not run Composer as root/super user! See https://getcomposer.org/root for details
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] mysqld (mysqld 10.2.25-MariaDB-1:10.2.25+maria~bionic) starting as process 1 ...
goteo-php    | Loading composer repositories with package information
goteo-php    | Installing dependencies (including require-dev) from lock file
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Uses event mutexes
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Compressed tables use zlib 1.2.11
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Using Linux native AIO
goteo-php    | Nothing to install or update
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Number of pools: 1
goteo-php    | Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
goteo-php    | Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
goteo-php    | Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
goteo-php    | Package guzzle/plugin-mock is abandoned, you should avoid using it. Use guzzle/guzzle instead.
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Using SSE2 crc32 instructions
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Completed initialization of buffer pool
goteo-mariadb | 2019-06-27 16:33:04 140418555844352 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
goteo-php    | Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
goteo-php    | Package omnipay/omnipay is abandoned, you should avoid using it. Use league/omnipay instead.
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Highest supported file format is Barracuda.
goteo-php    | Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: 128 out of 128 rollback segments are active.
goteo-php    | Generating autoload files
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Creating shared tablespace for temporary tables
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: Waiting for purge to start
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] InnoDB: 5.7.26 started; log sequence number 14198318
goteo-mariadb | 2019-06-27 16:33:04 140417915942656 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] Plugin 'FEEDBACK' is disabled.
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] Server socket created on IP: '::'.
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Warning] 'proxies_priv' entry '@% root@0a91251e30b8' ignored in --skip-name-resolve mode.
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] Reading of all Master_info entries succeeded
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] Added new Master_info '' to hash table
goteo-mariadb | 2019-06-27 16:33:04 140419278329152 [Note] mysqld: ready for connections.
goteo-mariadb | Version: '10.2.25-MariaDB-1:10.2.25+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
goteo-mariadb | 2019-06-27 16:33:04 140417915942656 [Note] InnoDB: Buffer pool(s) load completed at 190627 16:33:04
goteo-geoip  | Received an unexpected HTTP status code of 401 from https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=9ac3d817a071f829093bd1fbce8b2cb1&user_id=999999&edition_id=GeoLite-Legacy-IPv6-City
goteo-geoip  | geoipupdate 2.2.2
goteo-geoip  | Opened License file /etc/GeoIP.conf
goteo-geoip  | UserId 999999
goteo-geoip  | LicenseKey 000000000000
goteo-geoip  | Insert product_id GeoLite2-City
goteo-geoip  | Insert product_id GeoLite2-Country
goteo-geoip  | Insert product_id GeoLite-Legacy-IPv6-City
goteo-geoip  | Insert product_id GeoLite-Legacy-IPv6-Country
goteo-geoip  | Insert product_id 506
goteo-geoip  | Insert product_id 517
goteo-geoip  | Insert product_id 533
goteo-geoip  | Read in license key /etc/GeoIP.conf
goteo-geoip  | Number of product ids 7
goteo-geoip  | url: https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite2-City
goteo-geoip  | md5hex_digest: 9487ebee4f31b48d34c04f8a329241db
goteo-geoip  | url: https://updates.maxmind.com/app/update_getipaddr
goteo-geoip  | Client IP address: 187.178.88.99
goteo-geoip  | md5hex_digest2: 9ac3d817a071f829093bd1fbce8b2cb1
goteo-geoip  | url: https://updates.maxmind.com/app/update_secure?db_md5=9487ebee4f31b48d34c04f8a329241db&challenge_md5=9ac3d817a071f829093bd1fbce8b2cb1&user_id=999999&edition_id=GeoLite2-City
goteo-geoip  | No new updates available
goteo-geoip  | url: https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite2-Country
goteo-geoip  | md5hex_digest: 036000d00798df0b9783c7a378afce18
goteo-geoip  | url: https://updates.maxmind.com/app/update_getipaddr
goteo-geoip  | Client IP address: 187.178.88.99
goteo-geoip  | md5hex_digest2: 9ac3d817a071f829093bd1fbce8b2cb1
goteo-geoip  | url: https://updates.maxmind.com/app/update_secure?db_md5=036000d00798df0b9783c7a378afce18&challenge_md5=9ac3d817a071f829093bd1fbce8b2cb1&user_id=999999&edition_id=GeoLite2-Country
goteo-geoip  | No new updates available
goteo-geoip  | url: https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite-Legacy-IPv6-City
goteo-geoip  | md5hex_digest: 00000000000000000000000000000000
goteo-geoip  | url: https://updates.maxmind.com/app/update_getipaddr
goteo-geoip  | Client IP address: 187.178.88.99
goteo-geoip  | md5hex_digest2: 9ac3d817a071f829093bd1fbce8b2cb1
goteo-geoip  | url: https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=9ac3d817a071f829093bd1fbce8b2cb1&user_id=999999&edition_id=GeoLite-Legacy-IPv6-City
goteo-geoip exited with code 1
goteo-php    | Oops, exception thrown while running command migrate
goteo-php    | Command Exception
goteo-php    | 	error: Database goteo is not empty! Cannot install
goteo-php    | 
goteo-php    | You may want to execute:
goteo-php    | php bin/console migrate all
goteo-php    | 	command: migrate
goteo-php    | 	options: Array
goteo-php    | 	trace: Exception: Database goteo is not empty! Cannot install
goteo-php    | 
goteo-php    | You may want to execute:
goteo-php    | php bin/console migrate all
goteo-php    |  at Goteo.Console.Command.SqlMigrationCommand.execute(SqlMigrationCommand.php:123)
goteo-php    |  at Symfony.Component.Console.Command.Command.run(Command.php:245)
goteo-php    |  at Symfony.Component.Console.Application.doRunCommand(Application.php:853)
goteo-php    |  at Symfony.Component.Console.Application.doRun(Application.php:185)
goteo-php    |  at Symfony.Component.Console.Application.run(Application.php:117)
goteo-php    |  at (main)(console:66)
goteo-php    | 
goteo-php    |                                                
goteo-php    |   [Exception]                                  
goteo-php    |   Database goteo is not empty! Cannot install  
goteo-php    |                                                
goteo-php    |   You may want to execute:                     
goteo-php    |   php bin/console migrate all                  
goteo-php    |                                                
goteo-php    | 
goteo-php    | migrate [-u|--update] [-d|--debug] [-c|--config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--logmail] [--lock] [--lock-name [LOCK-NAME]] [--] <command> [<cmd>] [<name>]
goteo-php    | 
goteo-php    | >> Using Host from settings: 0.0.0.0
goteo-php    | >> Using local port from settings: 8081
goteo-php    | >> CURRENT DIR /application
goteo-php    | >> using PHP php-fpm7.1
goteo-php    | 
goteo-php    | Running "clean:server" (clean) task
goteo-php    | >> 8 paths cleaned.
goteo-php    | 
goteo-php    | Running "copy:devel" (copy) task
goteo-php    | Created 587 directories, copied 3034 files
goteo-php    | 
goteo-php    | Running "copy:plugins:devel" (copy:plugins) task
goteo-php    | 
goteo-php    | Running "sass:devel" (sass) task
goteo-php    | 
goteo-php    | Done.
goteo-php    | 
goteo-php    | 
goteo-php    | Execution Time (2019-06-27 16:33:11 UTC-0)
goteo-php    | loading tasks   1.2s  ▇▇▇▇ 8%
goteo-php    | clean:server   493ms  ▇▇ 3%
goteo-php    | copy:devel      2.2s  ▇▇▇▇▇▇▇ 14%
goteo-php    | sass:devel     11.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 75%
goteo-php    | Total 15.6s
goteo-php    | 
goteo-php    |  Pointing nginx server as DEVELOPMENT (index_dev.php)
goteo-php    | *************************************
goteo-php    |  System ready!
goteo-php    | 
goteo-php    |  You can point your browser now to:
goteo-php    | 
goteo-php    |  //0.0.0.0:8081
goteo-php    | 
goteo-php    |  Check all mailing activity in:
goteo-php    | 
goteo-php    |  localhost:8082
goteo-php    | 
goteo-php    | *************************************
goteo-php    | [27-Jun-2019 16:33:26] ERROR: [pool www] please specify user and group other than root
goteo-php    | [27-Jun-2019 16:33:26] ERROR: FPM initialization failed
goteo-php exited with code 0
goteo-webserver | 2019/06/27 16:33:35 [error] 6#6: *2 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "0.0.0.0:8081"

**Comment by davidbeig** [comment]
Hi!

Your error seems to come from the goteo-webserver, which is, in this case, a nginx installation. The nginx.conf is in docker/nginx/nginx.conf and it tries to connect to the php instance via the bridge docker creates.

It tries to reference php:9000 but it's not answering as the FPM initialization failed.

If i'm not wrong, that error is because you executed docker/up with sudo privileges. In the documentation we explain how to make it run without sudo.

[Docker install](https://goteofoundation.github.io/goteo/docs/developers/docker.html)
"👉 This script assumes to run docker-compose without root privileges. Its important for the user running docker to belong to the docker group. As is explained in the Post-installation steps in docker.com (just run sudo usermod -aG docker $USER to be sure)." 

Make sure to follow all the steps.

If you do so I think you won't have that problem again.

**Comment by raulsibaja7** [comment]
Hi David
Thank you for your prompt response! 
sudo in docker/up was the problem.

Regards
