### ISSUE TITLE
Defaul Language is not Spanish

### ISSUE THREAD

**Issue by fintecheand0** [GoteoFoundation/goteo#125]
Hi,

I have in the settings.yml the entry

lang: es

But when I go to the default page, always shows English as default langue, unless I change to Spanish.

Is there any there file that should be changed?

Regards

Victor

**Comment by microstudi** [comment]
Probably due your browser configuration. Check if you have your browser to show content in english first.
Also, check your preferences if you are logged in.

**Comment by fintecheand0** [comment]
Thank you.

We found that we got a bad configuration in the setting.yml

We had in 

lang: es
main: //ourdomain.com

for us now it is working with these settings:

lang: es
main: http://ourdomain.com

After that the language is shown by default in Spanish
