### ISSUE TITLE
Error when creating new projects

### ISSUE THREAD

**Issue by gekubo** [GoteoFoundation/goteo#13]
Cannot add or edit 'Breakdown of expenses' when creating a new project
[Capture →](http://sendvid.com/x0fz8aw8)

@microstudi
___
Godaddy Deluxe Plan
Linux Share Hosting PHP5 MySQL

**Comment by Agarba** [comment]
Hi, did you find a solution ?

**Comment by gekubo** [comment]
Hi @Agarba. I think updating the code to the last version should fix this problem
