### ISSUE TITLE
Upgrade to current Symfony Version?

### ISSUE THREAD

**Issue by DoktorDoener** [GoteoFoundation/goteo#146]
Hi guys,

are there any plans for upgrading to a current version of Symfony? 

Thx

**Comment by davidbeig** [comment]
Hi!

We would love to do have the time to take care of this, as well as upgrading for newer versions of php. It will be in our roadmap for next year, but can't say when we will deal with it.

In any case, if you do any advance in this topic we will be really glad to hear from you!

Best regards,
David

**Comment by Hanleymade** [comment]
> Hi!
> 
> We would love to do have the time to take care of this, as well as upgrading for newer versions of php. It will be in our roadmap for next year, but can't say when we will deal with it.
> 
> In any case, if you do any advance in this topic we will be really glad to hear from you!
> 
> Best regards,
> David

Wondering if there's been any progress in regards to Symfony / PHP upgrades?

**Comment by davidbeig** [comment]
Hi @Hanleymade,

We could not make any progress in this matter. With the pandemia and all our focus this past year has been to help the projects that have reached us and add new features that they might need.

Nonetheless, this upgrade is definitely something that we have to face any time soon.

**Comment by carlos-mg89** [comment]
@Hanleymade now Symfony 4.4 (LTS version with still security fixes being applied) is the base version.
