### ISSUE TITLE
Setting category to a project

### ISSUE THREAD

**Issue by getsei** [GoteoFoundation/goteo#147]
HI,

Where do we set a category (Social, Communications, Technological etc) to a project? I couldn't find it in the admin panel.

Thanks.

**Comment by davidbeig** [comment]
Hi!
You can set a social commitment to a project, to do so you have to enter in the project's dashboard.
![image](https://user-images.githubusercontent.com/41389482/72426281-bbdb9a80-3789-11ea-8077-a3105aea0574.png)

**Comment by getsei** [comment]
Thanks.
