### ISSUE TITLE
Missing File view_commons.html.php 

### ISSUE THREAD

**Issue by rajanbarara** [GoteoFoundation/goteo#159]
File - view_commons.html.php - is missing in Resources/templates/legacy/project/edit/rewards/

Actually there is no rewards directory under Resources/templates/legacy/project/edit/

Is this by design or just missing component ?

**Comment by davidbeig** [comment]
Hi @rajanbarara.

This controller is deprecated. We should delete it sooner or later. Sorry for the inconvenience.
