### ISSUE TITLE
I am installing Goteo with docker not working. Please help.

### ISSUE THREAD

**Issue by konyilwin** [GoteoFoundation/goteo#162]
Hello,

I am following this articles 
https://goteofoundation.github.io/goteo/docs/developers/docker.html
to  install Goteo with docker. But, after installing, this error show me. 
How do I fix this? Pls everybody help me. 

![image](https://user-images.githubusercontent.com/30022185/103080758-ed4d1f00-4604-11eb-892e-88f879202a5c.png)

**Comment by davidbeig** [comment]
Hi @konyilwin,

With that little information i cannot help you. Could you provide more details?

Since your problem is it cannot find the autoload, and it can be found in the vendor folder, maybe it's about the composer... can you check all dependencies have been downloaded?

**Comment by Erdenejargal-dev** [comment]
@davidbeig hello. What is version of grunt-contrib-compress . i have same error

**Comment by Erdenejargal-dev** [comment]
@konyilwin are u fixed ??? i have it (error) pls help me

**Comment by yoan34** [comment]
I have this issue and fixe it by delete all image in my computer "docker rmi -f $(docker images -aq)" and re start le project.

**Comment by carlos-mg89** [comment]
This error happens when you don't use the `docker/up` command to create the Docker environments.
