### ISSUE TITLE
Livereload issue

### ISSUE THREAD

**Issue by Agarba** [GoteoFoundation/goteo#17]
Everytime I try to create an account or a project, I get this error

`GET http://localhost:35729/livereload.js net::ERR_CONNECTION_REFUSED`

Do you have a solution for this issue ? 

Here is a screenshot :
![goteoissue](https://cloud.githubusercontent.com/assets/11680408/24301832/ea925f6a-10b0-11e7-97a0-bed4b5f4b399.JPG)

**Comment by microstudi** [comment]
This script is not really important, it's just to reload the page some server script has changed. It's for developing. 
What commands are you using to run goteo? Have you followed the install procedure, install npm packages, etc?

**Comment by Agarba** [comment]
Hi,

I've got everything install on a Vagrant to run the project.

To run goteo I do :
vagrant up
vagrant ssh 
grunt serve
-> then I connect to my localhost:8082

I did follow the install procedure but I still get this error

**Comment by microstudi** [comment]
thanks, it's been a while since I tested the vagrant installation. 
I'll look into it and I let you know.

**Comment by Agarba** [comment]
Hi, 

For your information I tried on Firefox, It works quite fine.
 
![goteoissue_itworksonfirefox](https://cloud.githubusercontent.com/assets/11680408/24748873/66f9b174-1ac1-11e7-8b3f-93ea46b02f3e.JPG)

Livereload.js works. 

So I'm going to continue testing on firefox instead of google chrome
Thanks again
