### ISSUE TITLE
Can't create a project on "devel" branch

### ISSUE THREAD

**Issue by Agarba** [GoteoFoundation/goteo#18]
To reproduce the bug, create a project (after creating an account) by following the form when you arrive and select "social commitment none" the screen gets gray.
Then you cannot do anything to go to the next step. you are bloqued

![bug_project_gif](https://cloud.githubusercontent.com/assets/11680408/25046160/40576c62-2130-11e7-9961-659d986553a7.gif)

**Comment by HTCode** [comment]
I got the same issue, any fixes ? Is there any more stable version ?

**Comment by javicarrillo** [comment]
Hi, It isn't a bug, you have to add a social commitment using the admin before (/admin/social_commitment). The social commitment is compulsory in Goteo, if you don't have a social commitment, you can't create a project.

**Comment by HTCode** [comment]
@javicarrillo I couldn't find this page from the admin panel menu, I needed to type the url directly. Now I filled the form (with the root user), but when I click "save and continue", I get an exception:
Fatal error: Cannot use Goteo\Model\Image as Image because the name is already in use in C:\wamp64\www\goteo\src\Goteo\Model\Project\Category.php on line 15

**Comment by Reaper45** [comment]
@Agarba, @javicarrillo  I think its  bug. calling the `parseContent()` method on `$term` at line 138 in `Resources/templates/responsive/project/create.php` deletes one of the closing `</div>` tags. Thus nesting the `#noSocialModal` modal into `#termsModal` modal. The 'Choose your social commitment' action only shows the backdrop i.e blank page.
Suggested Solution: 
Add a extra `</div>` at the ed of `#termsModal` modal. or 
Concatenate a `</div>` at line 162 of `/src/Goteo/Model/Page.php`  i.e, `return $this->content."</div>"`.

**Comment by microstudi** [comment]
I've commited some changes to the create project view in order to improve the keyboard experience.
About the </div> thing, it's more likely that the html code inside the `content` field in the tables `page`, `page_lang` (id: `howto`) is wrong.
Actually we don't use HTML in that field anymore, we use markdown now. Please update the field according this entries in `data.sql` (convert it to an UPDATE statement):

```sql
INSERT INTO `page`(`id`,`name`,`description`,`type`,`url`,`content`) VALUES ('howto','Instrucciones para ser productor/a',"4 condiciones y 2 requisitos para proponer un proyecto",'md','/about/howto','Goteo es una plataforma para apoyar proyectos cívicos, éticos y abiertos de ciudadanos, emprendedores, innovadores sociales y creativos cuyos objetivos, formato y/o resultado final ofrezcan, de forma total o significativa, algún tipo de retorno colectivo.

 **Condiciones**

*  Cuando mi proyecto ofrezca recompensas individuales a cambio de aportaciones económicas determinadas, deberé cumplir con el compromiso establecido con la plataforma y mis cofinanciadores en caso de obtener la financiación mínima solicitada.
*  Deberé cumplir igualmente con el compromiso de publicar los retornos colectivos prometidos, enlazándolos posteriormente desde la plataforma Goteo bajo la licencia elegida en el momento de solicitar la financiación, en cumplimiento de un contrato legal con la Fundación Goteo que firmaré en cuanto obtenga la financiación mínima.
*  Solicitaré una cofinanciación mínima para llevar a cabo el proyecto y otra óptima. En ambos casos desglosando una estimación aproximada del tipo de costes previstos y su cuantía.
*  La finalidad del proyecto no es la venta encubierta de productos o servicios ya producidos, ni la financiación de campañas delictivas o que atenten contra la dignidad de las personas.

**Requisitos**

* Soy mayor de 18 años.
*  Dispongo de una cuenta bancaria.

Para obtener más información sobre cualquiera de los puntos anteriores es importante que leas [nuestras FAQ](/faq).');
```
and:

```sql
INSERT INTO `page_lang`(`id`,`lang`,`name`,`description`,`content`,`pending`) VALUES ('howto','en','Instructions for project owners',"4 conditions and 2 requirements before submitting a project","Goteo is a platform for supporting projects created by entrepreneurs, social innovators, and creatives whose goals, format, or final result include, either wholly or in a significant amount, some type of collective benefit.

 **Terms**

*  When my project offers individual rewards in exchange for specific economic contributions, I will fulfill my obligations established with the platform and with my co-financiers after having received the minimum financing requested.
*  I will also fulfill my obligation to publish the promised collective benefits, linking them from the Goteo platform under the license chosen when financing was requested, as a fulfillment of my legal contract with Fundación Fuentes Abiertas.
*  I will request a minimum amount of co-financing to carry out my project, as well as an optimum amount. When I receive the minimum co-financing amount, I will begin production, about which I will file periodic reports, which will allow me to undertake a second round of co-financing en route to the optimum amount.
*  The end goal for the project is not the hidden sale of existing products or services, nor to finance criminal activity or to violate any person's dignity.

**Requirements**

*  I am at least 18 years of age.
*  I have a bank account in Spain or a PayPal account
Note: Those who do not have a bank account in Spain will only be able to use PayPal's payment system.

If you need more information about any of the following points, we recommend that you begin by reading [our FAQ](/faq).",0);
```

**Comment by HTCode** [comment]
By the way, after creating a project and evaluating it (using root account), how can I publish it ? The project is still under status "revision in progress" : 
![evaluateproject](https://user-images.githubusercontent.com/13835926/27158532-59a2bfc8-515f-11e7-98cc-bbd448468005.png)

**Comment by HTCode** [comment]
After creating a project and reviewing/evaluating it (using root account), how can I publish it ? The status is still "Under Evaluation" after the evaluation is finished:
![evaluateproject](https://user-images.githubusercontent.com/13835926/27159246-876a732a-5163-11e7-89ee-1c4825438615.png)

**Comment by microstudi** [comment]
root account should not be used. Kind of deprecated thing.
I don't recommend to use the "evaluatin" system, just go to projects and publish it (or from the user account publish the project).
