### ISSUE TITLE
Improve `YamlSettingLoader`

### ISSUE THREAD

**Issue by microstudi** [GoteoFoundation/goteo#188]
- [ ] Add a processing step after loading a file to extract matches like `%env(SOMETHING)%` and change its value ot the same corresponding ENV var specified in the environment (`getenv("SOMETHING")`)
![image](https://user-images.githubusercontent.com/1401520/124480206-51685100-dda7-11eb-850e-31e41edbc966.png)

We don't need the extra processing capabilites present in new versions of symfony (but we want to be compatible for the future)

**Comment by carlos-mg89** [comment]
Closing issue since it was implemented in https://github.com/GoteoFoundation/goteo/pull/189
