### ISSUE TITLE
What is the stable version of Goteo that I can use in production?

### ISSUE THREAD

**Issue by HTCode** [GoteoFoundation/goteo#19]
I tried the devl version (last version 3.09) of Goteo, but there are way too much bugs. Is there any stable version that I can use ? (like the one used on the official website).

**Comment by microstudi** [comment]
The 3.09 version is the same used in the official website.
However we have a big database full of the historic background. Most of the bugs are related to some of this components of this database being empty. Others are just bugs that happens on very specific situations. 
We are a very small team, It's hard for us to test all different cases, so we do what we can when we can. 
Pull requests would be much appreciated to solve bugs.

**Comment by HTCode** [comment]
@microstudi I faced bugs (that are not very specific) which are not related to empty data in the database. For example, simply by filling the form to create a project and clicking "save and continue", I have a Fatal error: Cannot use Goteo\Model\Image as Image because the name is already in use in C:\wamp64\www\goteo\src\Goteo\Model\Project\Category.php on line 15

![error](https://cloud.githubusercontent.com/assets/13835926/26150141/63b3ffd6-3afd-11e7-89c1-2f3cf2879488.png)

Note that in settings.yml I have
```
url:
    main: http://crowdfund
    assets: http://crowdfund/dist
    url_lang:
    data:
```

**Comment by microstudi** [comment]
ok, I look into it this week. I promise

**Comment by HTCode** [comment]
@microstudi Thanks. If you need it, I can make a short video showing all the errors that I faced. Would that be helpful (maybe to reproduce them) ?

**Comment by microstudi** [comment]
sure, go ahead, never hurts to have more information

**Comment by HTCode** [comment]
@microstudi Are there any news regarding the bugs? As you can see, I have made a video where I show the different problems/bugs that appears after installation. Please take a look at the video here: https://www.youtube.com/watch?v=GcHfGg_quf8

1) First, by simply clicking on "project passing today" (url /project/project-passing-today), it shows a php error. See image below:
![err1](https://cloud.githubusercontent.com/assets/13835926/26372470/5f384bd2-3ffe-11e7-83d3-886131f4ca4c.png)

2) Second, by login as root, then clicking on "Review panel" in the menu (url /review), it shows a php error. See image below:
![err2](https://cloud.githubusercontent.com/assets/13835926/26372624/dc1111d4-3ffe-11e7-939b-4081a5ce75fb.png)

3) Third, after creating a new project, it shows an error similar to the one mentioned in point (1).

4) Finally, I don't know why but css is not always correctly adjusted, and it looks like the pages take too much time to load (too slow).

**Comment by HTCode** [comment]
> ok, I look into it this week. I promise
Any news ? @microstudi

**Comment by microstudi** [comment]
Sorry, working on it still
