### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by tjikaljedy** [GoteoFoundation/goteo#2]
Hi Ivan, 

After build latest version, I still  cannot login as root/root, the admin page not come out , the browser back to login page every time i did submit button,  No-error found

Thx

**Comment by tjikaljedy** [comment]
Finally i solve this problem, just added some of sub domain in host files

en, es refer to main domain or sub

Thx

**Comment by microstudi** [comment]
did you have in the `config/settings.yml` this var activated?:
`url_lang: ...`
 If this the case, the system will try to redirect you to the proper domain with a subdomain corresponding to your language.
You can always disable that conf var by commenting it, then no redirection should happen

**Comment by alexm** [comment]
Please, note that `config/local-vagrant-settings.yml` still has `url_lang: 0.0.0.0:8081` which doesn't make sense on a vagrant box with locally forwarded ports. Commenting that line just works as expected (root login works, etc.) so I'd like to suggest to have it commented by default.

**Comment by microstudi** [comment]
thanks!
