### ISSUE TITLE
Database misconfiguration: SQLSTATE[HY000] [1045] Access denied for user 'goteo'@'172.19.0.X' (using password: YES)

### ISSUE THREAD

**Issue by francesco-santini** [GoteoFoundation/goteo#206]
I installed goteo:live branch from GitHub an I used Docker to install it, but when I connect to X.X.X.X:8081, my browsers returns 

> Config error
> Error 500
> Database misconfiguration: SQLSTATE[HY000] [1045] Access denied for user 'goteo'@'172.19.0.4' (using password: YES)

and Goteo logs the same error

>goteo-mariadb | 2021-09-01  9:38:35 140520393053952 [Warning] Access denied for user 'goteo'@'172.19.0.4' (using password: YES)
>goteo-php    | 172.19.0.2 -  01/Sep/2021:09:38:35 +0000 "GET /index_dev.php" 200

My config file concerning the db section is

>db:
>   driver:   mysql     # Database driver (mysql)
>    host:     127.0.0.1 # Database host
>    port:     3306      # Database port
>    charset:  utf8mb4     # Database charset
>    database: goteo_test     # Database schema (database name)
>   username: goteo      # Database user for the goteo database
>    password: password      # Password for the goteo database

Before running Goteo I ran 

>docker-compose exec 127.0.0.1 mysql -uroot -pcrowdfunding -e 'CREATE DATABASE goteo_test;'
>docker-compose exec 127.0.0.1 mysql -uroot -pcrowdfunding -e "GRANT ALL PRIVILEGES ON goteo_test.* TO 'goteo'@'%';"
>GOTEO_CONFIG_FILE='config/test-docker-settings.yml' docker/exec bin/console migrate install

And I got no output (everything was ok (?))

Finally, when I docker/up Goteo I get this fatal below

>goteo-php    | Fatal error: Uncaught Goteo\Application\Config\ConfigException: Database misconfiguration: >SQLSTATE[HY000] [2002] Connection refused in /application/src/Goteo/Core/DB.php on line 72
>goteo-php    | 
>goteo-php    | Goteo\Application\Config\ConfigException: Database misconfiguration: SQLSTATE[HY000] [2002] Connection refused in /application/src/Goteo/Core/DB.php on line 72
>goteo-php    | 
>goteo-php    | Call Stack:
>goteo-php    |     0.0002     403144   1. {main}() /application/bin/console:0
>goteo-php    |     0.0068    1698504   2. Goteo\Application\Config::load($config_file = 'config/settings.yml') /application/bin/console:33
>goteo-php    | 
>goteo-php    | PHP Fatal error:  Uncaught Goteo\Application\Config\ConfigException: Database misconfiguration: SQLSTATE[HY000] [2002] Connection refused in /application/src/Goteo/Core/DB.php:72
>goteo-php    | Stack trace:
>goteo-php    | #0 /application/src/Goteo/Core/Model.php(78): Goteo\Core\DB->__construct()
>goteo-php    | #1 /application/src/Goteo/Application/Config.php(75): Goteo\Core\Model::factory()
>goteo-php    | #2 /application/bin/console(33): Goteo\Application\Config::load()
>goteo-php    | #3 {main}
>goteo-php    |   thrown in /application/src/Goteo/Core/DB.php on line 72

I checked the closed issues and I found a post similar to this, but no answer to that.

Thanks!

**Comment by carlos-mg89** [comment]
I think you might have forgotten to create the goteo database. I only see goteo_test but not goteo, and that's the one you've received a complaint:

`goteo-mariadb | 2021-09-01 9:38:35 140520393053952 [Warning] Access denied for user 'goteo'@'172.19.0.4' (using password: YES)`

Try setting goteo and not goteo_test in your config too:

> database: goteo # Database schema (database name)

The DB goteo_test is intended exclusively to run PHPUnit tests.

Take care

**Comment by francesco-santini** [comment]
Thanks,
I first created the database from inside the mariadb docker

> docker exec -it <mariadb_container_id> bash

and then I logged in to mysql

>  mysql -u root -p

and I created the goteo database (which needs to be empty before starting all the containers)

> create database goteo;

and I created a got user giving him all the privileges over the got database:

> CREATE USER 'goteo'@'' IDENTIFIED BY 'password';
> GRANT ALL PRIVILEGES ON goteo.* TO 'goteo'@;

After docker/up the db is populated with all the needed tables.
