### ISSUE TITLE
File all.ac883e08.css instead of all.css in dist/assets/css/ and admin menu not appearing

### ISSUE THREAD

**Issue by HTCode** [GoteoFoundation/goteo#27]
After building the project (grunt build), the directory dist/assets/css does not contain a file all.css which poses some problems, it rather contains a file called all.ac883e08.css that I need to manually rename to all.css.

Also, when I go to the url mywebsite/admin, there is nothing that appears, only a message "
Please select an option from the menu" is appearing.

**Comment by microstudi** [comment]
This is the expected behaviour. We use this randomized names to solve the problem with cached versions of the css assets if using CDN.
The same `grunt build` command should place 2 files with this asset name in it, these files:

```
dist/templates/default/partials/header/styles.php
dist/templates/responsive/partials/header/styles.php
```
Please check if are they generated

**Comment by HTCode** [comment]
But it seems that the css which is imported is all.css not the one with the randomized name.

What about the menu not appearing when we go to url mywebsite/admin ?
