### ISSUE TITLE
Enable to send the project. Send button is disabled (grayed out)

### ISSUE THREAD

**Issue by HTCode** [GoteoFoundation/goteo#28]
After filling the form for creating a project and previewing it, I am unable to send to the project as the Send button is disabled (grayed out) even if no errors are waiting for correction (It displays: There's 0 errors in total). See the following image:

![project](https://user-images.githubusercontent.com/13835926/27133747-329d1d6e-510b-11e7-86ed-45addb1337bb.png)

**Comment by HTCode** [comment]
This was just because the level of data that I entered didn't reach 80%. I wonder if it is possible to disable this or to just this threshold to less than 80% ?

**Comment by microstudi** [comment]
This will be disabled in the next version of Goteo (working on it right now).
