### ISSUE TITLE
Error pls help me

### ISSUE THREAD

**Issue by Erdenejargal-dev** [GoteoFoundation/goteo#292]
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "routes". in C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php:102 Stack trace: #0 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('routes') #1 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('routes') #2 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%routes%', Array) #3 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php(179): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%routes%', Array) #4 C:\goteo\vendor\symfony\dependency-injection\ContainerBuilder.php(1149) in C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php on line 102

**Comment by carlos-mg89** [comment]
@Erdenejargal-dev could you please provide more information? What steps have you followed to setup the project???

**Comment by Erdenejargal-dev** [comment]
@carlos-mg89 already fixed thank you. And again one error . i cant fixed help me :)
`Fatal error: Uncaught Error: Class 'Goteo\Application\Config' not found in C:\goteo\src\autoload.php:17 Stack trace: #0 C:\goteo\.tmp\index.php(19): require_once() #1 C:\goteo\var\php\router_dev.php(33): require_once('C:\\goteo\\.tmp\\i...') #2 {main} thrown in C:\goteo\src\autoload.php on line 17`

**Comment by wildlogics** [comment]
> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "routes". in C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php:102 Stack trace: #0 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('routes') #1 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('routes') #2 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php(189): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%routes%', Array) #3 C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php(179): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%routes%', Array) #4 C:\goteo\vendor\symfony\dependency-injection\ContainerBuilder.php(1149) in C:\goteo\vendor\symfony\dependency-injection\ParameterBag\ParameterBag.php on line 102

This happens when there is no database or the database can't be reached

**Comment by Erdenejargal-dev** [comment]
@wildlogics  Hello thank u . Already fixed this issue and now i have another error . Are u know it 
`Fatal error: Uncaught Error: Class 'Goteo\Application\Config' not found in C:\goteo\src\autoload.php:15 Stack trace: #0 C:\goteo\.tmp\index.php(19): require_once() #1 C:\goteo\var\php\router_dev.php(33): require_once('C:\\goteo\\.tmp\\i...') #2 {main} thrown in C:\goteo\src\autoload.php on line 15`

**Comment by carlos-mg89** [comment]
@Erdenejargal-dev how have you setup the project?

**Comment by Erdenejargal-dev** [comment]
@carlos-mg89  Hello i'am junior at coding.  And i want to create mini project . 
i dont know some setup . Can you help me i will share you on screen (Anydesk).

**Comment by Nomoo0603** [comment]
@Erdenejargal-dev alda bish setup error udig asugad bn. ahhahah
