### ISSUE TITLE
Found another ERROR

### ISSUE THREAD

**Issue by tjikaljedy** [GoteoFoundation/goteo#3]
Hi, i found another error during view of Admin panel seems this : 

View::getEngine()->useContext('admin/', [
                    'option'      => $option,
                    'admin_menu'  => $menu,
                    'all_roles'   => $all_roles,
                    'all_nodes'   => $all_nodes,
                    'admin_node'  => $admin_node,
                    'admin_nodes' => $admin_nodes,
                    'breadcrumb'  => $breadcrumb,
                ]);
the code inside AdminController.php, when the value of admin_menu use in Breadcrumb.php will be empty

Thx

**Comment by tjikaljedy** [comment]
I think, in route.php the session is gone when apps did routing

**Comment by microstudi** [comment]
thanks, I won't be able to correct this and other issues till the end of the week. After that I'll give you proper response!

**Comment by microstudi** [comment]
Hi, can you guide a little bit more about this? I don't understand the problem here.
Thanks!

**Comment by tjikaljedy** [comment]
Hi Ivan,

I am using goteo 3.0.1 from goteofoundation, the problem happen when i
login as admin , and all admin menu doesn't appear. For redirect issue i
solved that issue.

If you dont mine can you provided me private email, and my private email is
tjikaljedy@gmail.com

Thx

**Comment by microstudi** [comment]
I've just sent it to you

**Comment by microstudi** [comment]
This seems as a windows - foil related issue.
Does not seem to happen in a Linux environment. As doesn't really make much sense to run Goteo in a Windows enviroment I'm closing this issue.
