### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by RockHardJim** [GoteoFoundation/goteo#31]
Hi i have succesfully installed goteo on localhost but whenever i try logging in it simply redirects me back to the login page and when i enter wrong credentials it shows error but correct credentials its simply redirects me back to login menu

**Comment by RockHardJim** [comment]
i fixed the issue by moving the session start to the index.php under dist
`<?php
require_once __DIR__ . '/../src/autoload.php';
use Symfony\Component\HttpFoundation\Request;
use Goteo\Application\App;
use Goteo\Application\Config;
use Goteo\Application\Session;
Session::start('goteo-real', 3600);
//Public Web path
define('GOTEO_WEB_PATH', __DIR__ . '/');




ini_set('display_errors', 1);
error_reporting(E_ALL & ~E_NOTICE & ~E_USER_DEPRECATED); // for symfony user deprecated errors
// error handle needs to go after autoload
set_error_handler('Goteo\Application\App::errorHandler');

// Config file...
Config::load();

// Error traces
if(Config::get('debug')) {
    ini_set('display_errors', 1);
    App::debug(true);
}

//Get from globals defaults
App::setRequest(Request::createFromGlobals());

// Get the app
$app = App::get();

// handle routes, flush buffer out
$app->run();
`

**Comment by microstudi** [comment]
Please, post full error messages and specify which version of php are you using
