### ISSUE TITLE
Project evaluation pending

### ISSUE THREAD

**Issue by yoan34** [GoteoFoundation/goteo#310]
Hi, 
How to change the status of a project which has just been created, it is in **evaluation pending** and I cannot find in **bin/console** or in **localhost: 8081/admin** or in the doc the way to change the status of the project.

**Comment by davidbeig** [comment]
The status of a project can be modified through the side bar that an admin can see in the project landing. In the admin there's a module to handle the projects. Is one of the legacy modules we still have. It might not be translated to english, but there are some options to change the status of the project.

**Comment by yoan34** [comment]
Hi, thank you for your reply.

I just reread the docs and saw the root user, was able to access the admin page. I'm stuck on HTTP requests which take 3-4 minutes per request. I don't know how to fix this problem. I tried changing the `docker/php/overrides.conf` file but it doesn't change anything. I create an issue for this problem https://github.com/GoteoFoundation/goteo/issues/307
