### ISSUE TITLE
Can't Access Environment Variables 

### ISSUE THREAD

**Issue by dessHub** [GoteoFoundation/goteo#33]
I would like to set environment variables on external service like cpanel or heroku variables but I can't get it working. I have tried  '%VARIABLE_NAME%', '%env( VARIABLE_NAME)%'  both on settings.yml and config.php file.

**Comment by microstudi** [comment]
Sorry, I'm not sure I can help you with this.
However, it's possible to specify a configuration file with env variables in version v3.2 (just published):

```
export GOTEO_CONFIG_FILE='/my/path/my-settings.yml'
```
