### ISSUE TITLE
Issues running on Self-Hosted Server.

### ISSUE THREAD

**Issue by nightstryke** [GoteoFoundation/goteo#36]
So I installed this to see if I could get it working, but I seem to be having trouble. 

- The page is all white.
- The images are broken.
- Half the links do not work.

I am running this on a non-aws server. Any help would be greatly appreciated. I'd like to at least get the images functioning.

Thanks.

**Comment by microstudi** [comment]
You should provide more information for a such generic question.
Php version? Apache/nginx version/configuration? MySQL version? Server error logs?
did you follow the instructions? any error while executing those commands?
Can provide screenshots? etc...

**Comment by nightstryke** [comment]
I'm using nginx on debian 9.
I'm running the test server in localhost:8081 and visiting the site on that same machine, but when I try to use it on the local network serverip 192.168.1.162:8081 all the images disappear as does the formatting.

While I can read spanish well enough, is there a way to for goteo to run in english only?

**Comment by microstudi** [comment]
Then you should use `192.168.1.162:8081` instead of `localhost:8081` in your settings.yml. This way link will be build using that url instead of localhost.

The whole web is not translated yet, the admin part is still in spanish. It will be changed (we are working on a new one now), but it's going to be a while (2, 3 months I expect).

**Comment by nightstryke** [comment]
I have tried that, but the images and formatting keep disappearing or won't load properly cause i'm not using localhost:8081 or 127.0.0.1:8081 so I'm trying to figure out why images aren't loading properly.

@microstudi If there's anything I can do to help with the English translations let me know.

**Comment by pomaxa** [comment]
@microstudi I have the same issue; PHP7.0, apache2.4

**Comment by microstudi** [comment]
Both of you should show me your settings.yml (the part under `url:`).
And give some url examples please

**Comment by pomaxa** [comment]
@microstudi sorry for late response, but I figure out what was the problem. 
1) I was pointing apache to the root folder, not to the "dist"
2) https://github.com/GoteoFoundation/goteo/blob/3b876661d5733c6f6ec3093e95518807cea33df8/public/.htaccess#L6 <-- this configuration works on apache2.2. but won't work for apache 2.4

**Comment by microstudi** [comment]
Thanks for reporting, .htaccess is removed in the latest version.
There is an example of a apache2.4 configuration as well in var/php/apache2.4.conf
