### ISSUE TITLE
CAS or LDAP authentication

### ISSUE THREAD

**Issue by alexm** [GoteoFoundation/goteo#37]
I need to set authentication up with LDAP or preferably CAS, so I'm wondering whether HTTP basic authentication could be used in coordination with an Apache module (e.g. libapache2-mod-auth-cas) to achieve that.

I know there's support for OAuth, which could be also an option if our CAS server was more recent, but it's not currently available and won't probably be in the near future.

I also found `extend/private-zones/src/Goteo/Application/EventListener/BasicAuthListener.php`, that could be used as an example to build a new authentication method, I guess. But are there any other examples or pointers that explain how to add new authentication methods?

**Comment by microstudi** [comment]
Hi Alex,
Would you mind to explain what do you want to achieve?
I guess you want to synchronize an external user database using LDAP or CAS with the internal database? or just make the whole (or parts of the) website private (as the BasicAuthListener does) and then use the internal authentication.

Importing external users, should be done in a similar way that the Oauth works:
1. Redirect to external url => do the authentication => get tokens from the external service => check if user exists (by email usually) => create/authenticate user

I don't know to much about LDAP or CAS, but if you want to work on this I'll give you my full support (we can event met in Barcelona if you want).

PD: si encara estas a la UPC (AC) records al Juanjo!

**Comment by alexm** [comment]
Hi Ivan,
we need a platform at UPC BarcelonaTech to breed innovation projects and pick those that are backed by the community and fit for the institution. We think that Goteo may be such a platform and we'd like to tweak it for the next round of [Nexus24](https://www.upc.edu/nexus24) projects in a few months.

The users of the platform will be UPC members, so we need to authenticate them with LDAP or preferably CAS. The CAS work-flow would be pretty much what you describe above and a colleague already developed [a PHP integration for CAS](https://github.com/UPC/yii2-identitat-upc) that seems a good match for our case too.

We just set a Goteo test environment up so we can evaluate if it really matches our needs for the innovation platform. I'm sure we'll have a lot of questions, so we should probably meet. I'll keep you posted.

Thanks a lot!
Alex

PS: _Encara estic a la UPC (AC). Ja li donaré records al Juanjo de part teva._ 😊

**Comment by microstudi** [comment]
Sounds great!
be aware that it will be some major updates in the code next week and the next 2/3 months

**Comment by microstudi** [comment]
More thoughts about this:

I you decide to implement the CAS authentication method you could include it in the main code of Goteo, making it configurable via settings. This way we could incorporate this method directly in goteo.org to allow UPC users to authenticate there using this (same way as all the OAuth methods). I'd like that!

Doing that, In your copy of the code, you should develop a simple plugin to disable the other auth methods (so users can olny authenticate via CAS).

We can further discuss this if you finally decide to use this code.
BR

**Comment by alexm** [comment]
Developing the integration with CAS authentication through a Goteo plugin or extention to core and configurable via settings is the right thing to do, indeed.

Thanks!

**Comment by alexm** [comment]
FWIW, I have a working plugin for CAS authentication in my [cas-auth](https://github.com/alexm/goteo/tree/cas-auth) branch in case you'd like to [take a look](https://github.com/GoteoFoundation/goteo/compare/devel...alexm:cas-auth).

Before sending you a pull request for this plugin, I'd like to test it in production with real users. On the other hand, I'll also send a few smaller changes for the core source that we had to make.

**Comment by microstudi** [comment]
it looks great.
Some suggestions:

This views you overwrite shouldn't be modified in the core code, they can go to you plugin:
```
Resources/templates/responsive/invest/partials/reward_box.php
Resources/templates/responsive/invest/partials/reward_box_resign.php
```
move to:
```
extend/cas-auth/Resources/templates/responsive/invest/partials/reward_box.php
extend/cas-auth/Resources/templates/responsive/invest/partials/reward_box_resign.php
```

If you do that, the original view won't be used and it only will be changed when the plugin is used. Even better would be to have some variables in settings to allow some customization on this, something like that:
settings.yml:
```yaml
plugins:
    cas-auth:
       active: true
       remove_invest_box: true
      ...
```

Finally, the Currency should be refactored to something like the Lang class, allowing new Currencies to be added without touching the core code. But that's on me, I will change that and I let you know.

**Comment by microstudi** [comment]
Please try the latest version of the code. Now Currencies can be customized using the class Currency.
This class has been moved from Goteo\Library to Goteo\Application.
To reset the currencies, just execute:
`Goteo\Application\Currency::setCurrenciesAvailable(multidimensional array);`
To add currencies:
`Goteo\Application\Currency::addCurrency(array);`
It's a little improvement...

**Comment by alexm** [comment]
> This views you overwrite shouldn't be modified in the core code, they can go to you plugin:

Yes, they belong to a different plugin for our project. I hadn't
played with Goteo plugins at the time I made those changes in
core, but now I can move them to a new plugin for our case.

Thanks for the tip!

**Comment by alexm** [comment]
> Please try the latest version of the code. Now Currencies can be customized using the class Currency.

Will do, thanks a lot!

**Comment by alexm** [comment]
I created a [new project](https://github.com/UPC/goteo-cas-auth) with the CAS authentication plugin changes only. It doesn't contain any of the changes in goteo core that you mentioned (those will end up in a new plugin eventually). Thus, I consider this issue as resolved. Thanks!
