### ISSUE TITLE
The successful login again redirect to Login Page in Chrome browser

### ISSUE THREAD

**Issue by marshadshaheen** [GoteoFoundation/goteo#38]
I am using latest code from the goteo repo.
it is working fine in Internet Explorer and MS Edge but doesn't work with Chrome browser
When I try to login, after entering user or while entering password, it navigates to Cookies info page and if luckily I am allowed to press Login submit button it successfully authenticate (as i see in debug mode) but come back to login page again
any tip?

**Comment by microstudi** [comment]
Is it working with firefox?
please provide more info about your browser (version info) and your installation (php version), logs related and even screenshots if that can help me. Otherwise I'm affraid I can't help you

**Comment by marshadshaheen** [comment]
yes its work with internet explore, i didn't check with Firefox. It works with all when in real mode but in development/debug mode chrome doesn't work

**Comment by microstudi** [comment]
you should provide more information about your set up, php version, mysql version, etc. And report any log errors

**Comment by marshadshaheen** [comment]
with latest checkout this issue is no more
thanks a lot for your kind support
