### ISSUE TITLE
Fatal error: Uncaught Error, when in 'categories' menu, and click on 'NEW CATEGORY' then 'ADD' and 'SEE KEYWORDS'

### ISSUE THREAD

**Issue by damma-nya** [GoteoFoundation/goteo#39]
Fatal error: Uncaught Error: Call to undefined method Goteo\Model\Category::getList() in /var/www/got/src/Goteo/Controller/Admin/CategoriesSubController.php:246 Stack trace: #0 [internal function]: Goteo\Controller\Admin\CategoriesSubController->process('keywords', NULL, Array, NULL) #1 /var/www/got/src/Goteo/Controller/Admin/CategoriesSubController.php(44): call_user_func_array(Array, Array) #2 /var/www/got/src/Goteo/Controller/AdminController.php(211): Goteo\Controller\Admin\CategoriesSubController->keywordsAction(NULL, NULL) #3 /var/www/got/vendor/symfony/http-kernel/HttpKernel.php(135): Goteo\Controller\AdminController->optionAction('categories', 'keywords', NULL, NULL, Object(Symfony\Component\HttpFoundation\Request)) #4 /var/www/got/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/got/src/Goteo/Application/App.php(180): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\ in /var/www/got/src/Goteo/Controller/Admin/CategoriesSubController.php on line 246.

**Comment by microstudi** [comment]
would you mind to format a little bit better this message, and please specify the url originating this exception

**Comment by damma-nya** [comment]
http://website.url/admin/categories/add

**Comment by microstudi** [comment]
Can you check if this still happens with the last version?

**Comment by davidbeig** [comment]
Closing this issue because there was no response.
