### ISSUE TITLE
incoherence in sql files during install

### ISSUE THREAD

**Issue by floriancastagno** [GoteoFoundation/goteo#4]
When installing from scratch, the structure and data are not in coherence.

The ligne inserted in the user database contains the wrong number of value
the error is:

```
mysql -u root -p goteo < db/install/data.sql
ERROR 1136 (21S01) at line 542: Column count doesn't match value count at row 1
```

**Comment by microstudi** [comment]
Thanks for reporting. I've just patched the SQL file.
Please report if that solves the issue!

**Comment by floriancastagno** [comment]
You are welcome.
Not yet, another error:

```
ERROR 1452 (23000) at line 542: Cannot add or update a child row: a foreign key constraint fails (`goteo`.`user`, CONSTRAINT `user_ibfk_1` FOREIGN KEY (`node`) REFERENCES `node` (`id`) ON UPDATE CASCADE)
```

seems that the goteo is missing in node table

**Comment by cocoxinhxan** [comment]
run import before structure: db/install/upgrade-to-v3.0.3.sql

**Comment by attalias** [comment]
after data,sql  I get this error.

/*Data for the table `user` */ INSERT INTO  `user` (  `id` ,  `name` ,  `password` ,  `email` ,  `active` ,  `worth` ,  `created` ,  `token` ,  `hide` , `confirmed` ,  `lang` ,  `node` ) 
VALUES (

'root',  'Sysadmin',  '$1$L0HUgg5m$BFHWQWxOD/L3ekMBEIMVU.',  '', 1, 0, NOW( ) ,  '', 1, 1,  'en',  'goteo'
);

**Comment by microstudi** [comment]
Please test agains with the latests version, I've spent a while trying to correct this mistakes
