### ISSUE TITLE
responsive template

### ISSUE THREAD

**Issue by damma-nya** [GoteoFoundation/goteo#41]
I am using version 3.2, and I tried all the info in the documentation to get the responsive template to show, however no success so far.   
I place this in the setting.yml to activate the template
plugins:
    plugin-responsive:
                 active: true

responsive template is added to extend folder like so
 extend/plugin-responsive/Resources/templates/responsive
I also tried adding home/index to DiscoverController.php. and still the responsive template does not show, the only time it partially shows up is when I rename the default template however with 500 error on page.  could you tell me what I'm doing wrong here, and also send me some additional information or documents regarding adding the responsive template instead of the default one, via email  or via this thread on github.  If you choose to send this info via email, I will provide when you respond.

**Comment by microstudi** [comment]
Please upgrade to the last version, check the [documentation](http://goteofoundation.github.io/goteo/docs/developers/extend.html) again because I've improved it a little.

The new version has a responsive home.

**Comment by damma-nya** [comment]
I will view the new documentation and do the upgrade. Will reply when done so.

**Comment by damma-nya** [comment]
I'm already upgraded to the latest version.
Current schema version is 20171122174103
 Already up to date.

 I tried all the info in the documentation and responsive template not showing.  replicate responsive in the 'extend' directory: /extend/plugin-responsive/Resources/templates/responsive. 
In the directory /extend/plugin-responsive: I added the  start.php, manifest.yml files and 'src' directory copied from 'src' root directory, however don't have a 'Vendor' directory is it needed; do I need to rename the src/Goteo to src/plugin-responsive. 
------------------------------
In the manifest.yml file the code below is added
-----------------------------
name: plugin-responsive
version: 1.0
assets:
    # Will be copied as dist/plugin-name/assets
    Resources/assets: plugin-responsive/assets
------------------------------------------------------------
 and start.php is empty.
------------------------------------
activate plugin in setting.yml with code below
---------------------
plugins:
    plugin-responsive:
                 active: true
------------------------------------
still have the default home page with black tool bar at top of page and red  DISCOVER PROJECTS button , etc. showing, also after clearing browser cache and refresh page

**Comment by microstudi** [comment]
It maybe something wrong with your plugin.
Firts of all, if you only want to replace some views, you need a plugin with only 2 files, the `manifest.yml` and the `start.php` (which can be empty). 
The `manifest.yml` should be exactly like this:
```yaml
name: plugin-responsive
version: 1.0
```
(You don't need to specify any other resources for the moment: start simple).
the `start.php` may be like this:
```php
<?php
// plugin init file
```
That's right, nothing in it...

Then you can start overwriting views, for example create this file:
`extend/plugin-responsive/Resources/templates/responsive/home/partials/call_to_action.php`
With this content:
```html
<div class="section call-action">
    <div class="container">
        Check this out: <a class="btn btn-lg btn-orange pull-right" href="www.goteo.org">Goteo rocks</a>
    </div>
</div>
```

You should now view the home with a nice cyan bar with the new content added. You can repeat this process by adding more files with you custom content.
For example, you can create this file: `extend/plugin-responsive/Resources/templates/responsive/home/index.php` with anything you want in it and it will replace the default one.

I hope this make it more clear. 

Be aware that the views system uses Foil, so you may want to check the documentation here: https://foilphp.github.io/Foil/

**Comment by damma-nya** [comment]
I did all what is required and still responsive template is not showing. Also the https://foilphp.github.io/Foil/  links does not work.  Your explanation seems straightforward enough to follow. I'm just not having any success in deactivating the default template and activating the responsive template.  putting the responsive template folder in the extended folder and activating it in the setting.yml, then the other few things should overrides the default template, however not happening for me.

**Comment by microstudi** [comment]
Please note, that not all views are ported yet to responsive. We are working on it.
Is there any responsive view working? can you some screenshots of differents urls?
