### ISSUE TITLE
Please use int64 instead of int for money (virtual wallet )

### ISSUE THREAD

**Issue by mrtaurusp** [GoteoFoundation/goteo#49]
I'm planning on use Goteo for my crowdfunding website but I faced a problem: I need maximum value of money break up 2 billions. I didn't find on source code where is this variable and variable's type. Please have a check. Thanks.

**Comment by microstudi** [comment]
2 billion? 😱
what kind of project do you have in mind?
On the practical side, you're going to need to change the mysql database type everywhere where the amount (or similar) variables are found. Then you'll have to test it thoroughly and, after that, you may consider making a pull-request if you do it with the migration tool (But I'm a little sceptic about accepting it)
Some table-fields you'll need to change (but it may be others, you'll need to look more deeply into the database):
```
invest:  amount, amount_original
user_pool: amount
project: mincost, maxcost, amount, amount_users, amount_call
matcher: amount, used, crowd
call: amount, rest, used, applied
```

**Comment by mrtaurusp** [comment]
It's serious problem. $100.000 = 2 bills VND. I changed all int32 to int64, UInt32 to UInt64,... But it's still have int somewhere I can't find. So I create this issue. Thanks alots.

**Comment by microstudi** [comment]
I see, let me know if you get stuck somewhere.
When you finish I'd appreciate you to post here what fields have you finally changed.

**Comment by davidbeig** [comment]
Closing this issue because there was no response.
