### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by floriancastagno** [GoteoFoundation/goteo#5]
I installed from scratch using vagran following the documentation.
After trying to login with user: root and pass:  root, a red banner displaying Error is displayed.
There is no other particular message.
Any idea? maybe a wrong configuration?

**Comment by grib0** [comment]
The root password in the sql file data.sql is not the SHA1 for 'root'. Update the password from phpmyadmin with SHA1 mysql function solved the problem

**Comment by microstudi** [comment]
This should be solved now, it was compatibilit issue with the old configuration
