### ISSUE TITLE
Tabs in config/vagrant-settings.yml

### ISSUE THREAD

**Issue by grib0** [GoteoFoundation/goteo#6]
In the [environnement documentation page](http://goteofoundation.github.io/goteo/docs/developers/environment.html)
we have to copy the vagrant-settings.yml 

``` sh
cp config/vagrant-settings.yml config/settings.yml
```

There are lots of tabs in config/setting.yml leading to php error :

``` log
A YAML file cannot contain tabs as indentation at line 185 (near "  # Not recommended, there's a way in the admin to see all sent communications").
```

**Comment by microstudi** [comment]
This should be solved with the last version
