### ISSUE TITLE
Missing gap between links in "Cofinanciadores" section

### ISSUE THREAD

**Issue by sauloperez** [GoteoFoundation/goteo#67]
I just found a missing gap between the "ENVIAR UN MENSAJE..." and the export to CSV links below:

![captura de pantalla 2018-03-01 a les 13 53 14](https://user-images.githubusercontent.com/762088/36845737-265ba402-1d58-11e8-8814-32d8b8e97ef1.png)

**Comment by microstudi** [comment]
that should be fixed in the next release
