### ISSUE TITLE
When deploy code as Real- child pages not found

### ISSUE THREAD

**Issue by marshadshaheen** [GoteoFoundation/goteo#84]
Really strange Issue with latest Code. May be my mistake somewhere but I am doing same as I have done for previous codes.

old code is working find but I downloaded latest code three days back and tested it with grunt serve and it works fine on port 8081.
When I put deploy it with 'grunt build:dist' and point the root to new location, the website appears on 80 port but each other pages is not found message as given below
///////////////
Not Found
The requested URL /login was not found on this server.

Apache/2.4.18 (Ubuntu) Server at 104.237.133.24 Port 80
////////////////////////////

**Comment by marshadshaheen** [comment]
issue resolved. I had a mistake on security settings

**Comment by microstudi** [comment]
glad to know you've solve it.
