### ISSUE TITLE
Language of admin is not English even default language is English

### ISSUE THREAD

**Issue by marshadshaheen** [GoteoFoundation/goteo#87]
please help to change the language of Admin pages, i have change 'es' to 'en' in settings.yml config file. This change has changed user pages to English but admin pages are still with 'es'
thanks

**Comment by microstudi** [comment]
That's a problem we are currently addressing. The admin module it's not yet translated. The new admin is comming, but it will be a process. A first release with some submodules translates wont' be long to  be published

**Comment by marshadshaheen** [comment]
Thanks
please let me know I can participate to translate admin
I mean share the process to translate :)

**Comment by microstudi** [comment]
At this point we don't have the resources to change the old administration modules but we are creating a new ones in a more modern interface that will have everything with proper localization (translatable via crowdin).
