### ISSUE TITLE
admin/categories/add error 

### ISSUE THREAD

**Issue by damma-nya** [GoteoFoundation/goteo#89]
admin/categories/add
when all fields are blank  and you press the 'add' button you get this error.

Fatal error: Uncaught Error: Class 'Goteo\Controller\Admin\Message' not found in /var/www/amya1/src/Goteo/Controller/Admin/CategoriesSubController.php:184 Stack trace: #0 [internal function]: Goteo\Controller\Admin\CategoriesSubController->process('edit', NULL, Array, NULL) #1 /var/www/amya1/src/Goteo/Controller/Admin/CategoriesSubController.php(56): call_user_func_array(Array, Array) #2 /var/www/amya1/src/Goteo/Controller/AdminController.php(211): Goteo\Controller\Admin\CategoriesSubController->editAction(NULL, NULL) #3 /var/www/amya1/vendor/symfony/http-kernel/HttpKernel.php(135): Goteo\Controller\AdminController->optionAction('categories', 'edit', NULL, NULL, Object(Symfony\Component\HttpFoundation\Request)) #4 /var/www/amya1/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/amya1/src/Goteo/Application/App.php(180): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Reque in /var/www/amya1/src/Goteo/Controller/Admin/CategoriesSubController.php on line 184

also when I add 'use Goteo\Controller\Message;' in  /Goteo/Controller/Admin/CategoriesSubController.php, it point to another error  /src/Goteo/Core/Traits/LoggerTrait.php on line 47 which I'm sure is not the real issue.

**Comment by davidbeig** [comment]
This issue was solved in this [commit](https://github.com/GoteoFoundation/goteo/commit/46af2c18a8bb876c121107042eceb299868ea077).

Closing years later.
