### ISSUE TITLE
error in /admin/categories

### ISSUE THREAD

**Issue by damma-nya** [GoteoFoundation/goteo#90]
error when press 'See Keywords'  the link is  admin/categories/keywords

Fatal error: Uncaught Error: Call to undefined method Goteo\Model\Category::getList() in /var/www/amya1/src/Goteo/Controller/Admin/CategoriesSubController.php:246 Stack trace: #0 [internal function]: Goteo\Controller\Admin\CategoriesSubController->process('keywords', NULL, Array, NULL) #1 /var/www/amya1/src/Goteo/Controller/Admin/CategoriesSubController.php(44): call_user_func_array(Array, Array) #2 /var/www/amya1/src/Goteo/Controller/AdminController.php(211): Goteo\Controller\Admin\CategoriesSubController->keywordsAction(NULL, NULL) #3 /var/www/amya1/vendor/symfony/http-kernel/HttpKernel.php(135): Goteo\Controller\AdminController->optionAction('categories', 'keywords', NULL, NULL, Object(Symfony\Component\HttpFoundation\Request)) #4 /var/www/amya1/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/amya1/src/Goteo/Application/App.php(180): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\ in /var/www/amya1/src/Goteo/Controller/Admin/CategoriesSubController.php on line 246

**Comment by davidbeig** [comment]
This issue was solved in this [commit](https://github.com/GoteoFoundation/goteo/commit/46af2c18a8bb876c121107042eceb299868ea077) from getList to getAll

Closing years later.
