### ISSUE TITLE
Local installation Windows

### ISSUE THREAD

**Issue by Ermandi** [GoteoFoundation/goteo#91]
Windows issue: when I follow the steps as described at goteo Documentation, the project opens but is not loading the default css files ex: all.css, call.css, home.css, vendor.css, home-vendor.css etc. CSS files are there but they are overwritten with numbers in the end of their name.

**Comment by microstudi** [comment]
This files are processed by grunt to generated a minimez version (whit that number in the file). Then the dist folder is updated with the changed lines in the html templates, I don't know if it works in Windows. It's not planned to support it either.
