### ISSUE TITLE
Local installation Linux

### ISSUE THREAD

**Issue by Ermandi** [GoteoFoundation/goteo#92]
From installation process of goteo locally in xampp in linux mint at this command "php bin/console migrate install" it throws exception MYSQL ,ATTIR

**Comment by microstudi** [comment]
Can you put all the output of the command?

**Comment by Ermandi** [comment]
Yes, here it is:
PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /opt/lampp/htdocs/src/Goteo/Core/DB.php:42
Stack trace:
#0 /opt/lampp/htdocs/src/Goteo/Core/Model.php(74): Goteo\Core\DB->__construct(Object(Goteo\Library\Cacher), 2)
#1 /opt/lampp/htdocs/src/Goteo/Application/Config.php(50): Goteo\Core\Model::factory()
#2 /opt/lampp/htdocs/bin/console(32): Goteo\Application\Config::load('/opt/lampp/htdo...')
#3 {main}
  thrown in /opt/lampp/htdocs/src/Goteo/Core/DB.php on line 42

**Comment by microstudi** [comment]
You need to enable mysql in your php installation. Search in google/stackoverflow for the PHP fatal error ('Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'') in your lampp installation (i never used that kind of php install)

**Comment by Ermandi** [comment]
now it seems the same error with other warnings:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo_mysql.dll' - /usr/lib/php/20151012/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /opt/lampp/htdocs/src/Goteo/Core/DB.php:42
Stack trace:
#0 /opt/lampp/htdocs/src/Goteo/Core/Model.php(74): Goteo\Core\DB->__construct(Object(Goteo\Library\Cacher), 2)
#1 /opt/lampp/htdocs/src/Goteo/Application/Config.php(50): Goteo\Core\Model::factory()
#2 /opt/lampp/htdocs/bin/console(32): Goteo\Application\Config::load('/opt/lampp/htdo...')
#3 {main}
  thrown in /opt/lampp/htdocs/src/Goteo/Core/DB.php on line 42

and I just followed steps described at goteo documention site : 
http://goteofoundation.github.io/goteo/docs/install.html

**Comment by microstudi** [comment]
This is an issue related to a bad PHP installation (you probably need to install the mysql mod and configure it), there's hundreds of tutorials explaining that.
If your are using linux mint (which is Ubuntu compatible) I'd recommend you to stick to the process explained in the docs to install php mysql. If you want to use the lampp, please google your error related to the context of lampp, I cannot provide you support for it.

**Comment by Ermandi** [comment]
Some of funcionalities that are on goteo.org are not available here, and i cannot find and test dhe Admin not for particular project but for all projects that are created and other options that admin can have access.
